AKDEM.OBYS.UI/Controllers/ScheduleController.cs
using AKDEM.OBYS.Business.Services;
using AKDEM.OBYS.Common;
using AKDEM.OBYS.Common.Enums;
using AKDEM.OBYS.Dto.AppScheduleDtos;
using AKDEM.OBYS.UI.Models;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AKDEM.OBYS.UI.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly IAppScheduleService _appScheduleService;
        private readonly IAppLessonService _appLessonService;
        private readonly IAppBranchService _appBranchService;
        private readonly IAppUserSessionService _appUserSessionService;
        private readonly IAppUserSessionLessonService _appUserSessionLessonService;
        private readonly IAppScheduleDetailService _appScheduleDetailService;
        private readonly IAppSessionService _appSessionService;
        private readonly IAppWarningService _appWarningService;
        private readonly IValidator<AppScheduleCreateModel> _appScheduleCreateModelValidator;


        public ScheduleController(IAppScheduleService appScheduleService, IAppLessonService appLessonService, IAppBranchService appBranchService, IAppUserSessionService appUserSessionService, IAppUserSessionLessonService appUserSessionLessonService, IAppScheduleDetailService appScheduleDetailService, IAppSessionService appSessionService, IAppWarningService appWarningService, IValidator<AppScheduleCreateModel> appScheduleCreateModelValidator)
        {
            _appScheduleService = appScheduleService;
            _appLessonService = appLessonService;
            _appBranchService = appBranchService;
            _appUserSessionService = appUserSessionService;
            _appUserSessionLessonService = appUserSessionLessonService;
            _appScheduleDetailService = appScheduleDetailService;
            _appSessionService = appSessionService;
            _appWarningService = appWarningService;
            _appScheduleCreateModelValidator = appScheduleCreateModelValidator;
        }

        public async Task<IActionResult> Index(int id)
        {
            var result = await _appScheduleService.GetSchedulesBySession(id);
            ViewBag.sessionId = id;
            ViewBag.sessionStatus2 = await _appSessionService.GetStatus2FromSessionId(id);
            return this.View(result);
        }
        public async Task<IActionResult> CreateSchedule(int id)
        {
            var list = new List<AppScheduleSelectModel>();
            var items = await _appBranchService.GetBranchListNotScheduleAsync(id);
            foreach (var item in items)
            {
                list.Add(new AppScheduleSelectModel
                {
                    Id = item.Id,
                    BranchDetail = item.Definition
                });
            }
            ViewBag.branches = new SelectList(list, "Id", "BranchDetail");
            ViewBag.sessionId = id;
            return View(new AppScheduleCreateModel());
        }
        [HttpPost]
        public async Task<IActionResult> CreateSchedule(AppScheduleCreateModel model)
        {
            var modelResult = _appScheduleCreateModelValidator.Validate(model);
            var list = new List<AppScheduleSelectModel>();
            var items = await _appBranchService.GetBranchListNotScheduleAsync(model.SessionId);
            foreach (var item in items)
            {
                list.Add(new AppScheduleSelectModel
                {
                    Id = item.Id,
                    BranchDetail = item.Definition
                });
            }
            ViewBag.branches = new SelectList(list, "Id", "BranchDetail");
            ViewBag.sessionId = model.SessionId;
            if (modelResult.IsValid)
            {
                AppScheduleCreateDto dto = new();
                dto.Definition = model.Definition;
                dto.SessionBranchId = await _appScheduleService.GetSessionBranchIdBySessionIdandBranchId(model.SessionId, model.BranchId);
                var result = await _appScheduleService.CreateScheduleAsync(dto);
                

                if (result.ResponseType == ResponseType.Success)
                {
                    ViewBag.message = 1;
                    ViewBag.sessionBranchId = dto.SessionBranchId;
                    ViewBag.branchId = model.BranchId;

                    return View(new AppScheduleCreateModel());
                }
                else
                {
                    foreach (var item in result.ValidationErrors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                    }
                    return View(result.Data);
                }

                
            }
            foreach (var error in modelResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            return View(model);



        }
        public async Task<IActionResult> RemoveSchedule(int scheduleId)
        {
            List<int> userIds = new List<int>();
            var branchId = await _appScheduleService.GetBranchIdByScheduleId(scheduleId);
            var sessionId = await _appScheduleService.GetSessionIdByScheduleId(scheduleId);
            var userSessionList = await _appUserSessionService.GetUserSessionsByBranchId(sessionId, branchId);
            foreach ( var userSessionId in userSessionList)
            {
                userIds.Add(await _appUserSessionService.GetUserIdByUserSessionId(userSessionId));
            }
            await _appUserSessionLessonService.RemoveUserSessionLessonsByUserSessionListAsync(userSessionList);
            
            await _appScheduleDetailService.RemoveScheduleDetailsByScheduleId(scheduleId);
            await _appScheduleService.RemoveScheduleByScheduleId(scheduleId);
            foreach ( var userId in userIds)
            {
                int userSessionId = await _appUserSessionService.UserSessionIdByUserIdAndSessionId(userId, sessionId);
                await _appWarningService.RemoveWarningByUserIdandSessionId(userId, sessionId,userSessionId);
                await _appUserSessionService.SetZeroToSessionAverage(userId, sessionId);
                await _appUserSessionService.TotalAverageByUserId(userId,sessionId);
            }
            
            return RedirectToAction("Index", new {id=sessionId });
        }

    }
}

AKDEM.OBYS.UI/Views/Schedule/CreateSchedule.cshtml
@model AppScheduleCreateModel
@{
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="text-left">
        <a class="btn btn-danger" asp-action="SessionDetails" asp-controller="Session" asp-route-id="@ViewBag.sessionId">Döneme Dön</a>
    </div>
    <hr />
    <h1 id="headertext">Program Oluştur</h1>
    <form asp-action="CreateSchedule" asp-controller="Schedule" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="SessionId" value="@ViewBag.sessionId" />

        <div id="divekle" class="mt-3">
            <label>Program İsmi :</label>
            <input id="inputDefinition" asp-for="Definition" type="text" class="form-control font-weight-bold" />
        </div>

        <div id="divclasses" class="mt-3">
            <label>Sınıf :</label>
            <select asp-for="BranchId" asp-items="@ViewBag.branches" class="form form-control-sm">
                <option value="0">Bir Sınıf Seçiniz</option>
            </select>
        </div>


        <div id="btnekle" class="mt-3">
            <button class="btn btn-primary" type="submit">Kaydet</button>
        </div>
        <br />
        <div id="btncreate" style="display:none" class="mb-3">
            <a class="btn btn-outline-info" asp-action="CreateScheduleDetail" asp-controller="ScheduleDetail" asp-route-sessionBranchId="@ViewBag.sessionBranchId">Çizelge Oluştur</a>
        </div>
        <div class="mb-3 text-bg-danger" asp-validation-summary="All">

        </div>
    </form>

</div>

@section script{ 
<script>
    var btnsave = document.getElementById("btnekle");
    var btncreate = document.getElementById("btncreate");

        if (@ViewBag.message==1) {
            
            @*alert("@ViewBag.alert");*@
            document.getElementById("inputDefinition").value = "";
            btnekle.style.display = "none";
            btncreate.style.display = "block";

            divclasses.style.display = "none";
            divekle.style.display = "none";
            document.getElementById("headertext").innerHTML = "Çizelge";

    }


</script>


}

AKDEM.OBYS.UI/Views/Schedule/Index.cshtml
@model List<AppScheduleListDto>
@{
    Layout = "_Layout";
}

<div class="mt-2">
    <h1>DERS PROGRAMLARI</h1>
</div>
@{ if (ViewBag.sessionStatus2)
    {
        <div class="text-right">
            <a asp-action="CreateSchedule" asp-controller="Schedule" asp-route-id="@ViewBag.sessionId" class="mt-2 btn btn-success">Yeni Program Ekle</a>
        </div>

    }
}

<br />
<table class="mt-3 table table-sm table-hover">
    <thead>
        <tr>
            <th>Dönem Adı</th>
            <th>Sınıf </th>
            <th>Program</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.AppSessionBranch.AppSession.Definition</td>
                <td>@item.AppSessionBranch.AppBranch.Definition</td>
                <td><a asp-action="Index" asp-controller="ScheduleDetail" asp-route-id="@item.Id" class="btn btn-info">@item.Definition</a></td>

            </tr>
        }
    </tbody>

</table>