AKDEM.OBYS.UI/Controllers/OtomationController.cs
using AKDEM.OBYS.Business.Services;
using AKDEM.OBYS.Dto.AppBranchDtos;
using AKDEM.OBYS.Dto.AppUserSessionDtos;
using AKDEM.OBYS.Dto.AppUserSessionLessonDtos;
using AKDEM.OBYS.Dto.AppWarningDtos;
using AKDEM.OBYS.UI.Models;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PuppeteerSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AKDEM.OBYS.UI.Controllers
{
    
    public class OtomationController : Controller
    {
        private readonly IAppBranchService _appBranchService;
        private readonly IAppStudentService _appStudentService;
        private readonly IAppUserSessionService _appUserSessionService;
        private readonly IAppUserSessionLessonService _appUserSessionLessonService;
        private readonly IAppWarningService _appWarningService;
        private readonly IAppLessonService _appLessonService;
        private readonly IAppSessionService _appSessionService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IAppUserService _appUserService;
        private readonly IValidator<AppUserSessionLessonUpdateDto> _appUserSessionLessonupdateDtoValidator;


        public OtomationController(IAppBranchService appBranchService, IAppStudentService appStudentService, IAppUserSessionService appUserSessionService, IAppUserSessionLessonService appUserSessionLessonService, IAppWarningService appWarningService, IAppLessonService appLessonService, IAppSessionService appSessionService, IWebHostEnvironment webHostEnvironment, IAppUserService appUserService, IValidator<AppUserSessionLessonUpdateDto> appUserSessionLessonupdateDtoValidator)
        {
            _appBranchService = appBranchService;
            _appStudentService = appStudentService;
            _appUserSessionService = appUserSessionService;
            _appUserSessionLessonService = appUserSessionLessonService;
            _appWarningService = appWarningService;
            _appLessonService = appLessonService;
            _appSessionService = appSessionService;
            _webHostEnvironment = webHostEnvironment;
            _appUserService = appUserService;
            _appUserSessionLessonupdateDtoValidator = appUserSessionLessonupdateDtoValidator;
        }
        char[] charactersToReplace = { '/', ' ', '\\', '?', ':', '.', ',' };
        char replacementChar = '_';
        static string ReplaceMultipleChars(string input, char[] charactersToReplace, char replacementChar)
        {
            foreach (char c in charactersToReplace)
            {
                input = input.Replace(c, replacementChar);
            }
            return input;
        }
        static string ConvertTurkishToEnglish(string input)
        {
            StringBuilder result = new StringBuilder();

            foreach (char c in input)
            {
                switch (c)
                {
                    case 'Ç':
                        result.Append('C');
                        break;
                    case 'Ğ':
                        result.Append('G');
                        break;

                    case 'İ':
                        result.Append('I');
                        break;
                    case 'Ö':
                        result.Append('O');
                        break;
                    case 'Ş':
                        result.Append('S');
                        break;
                    case 'Ü':
                        result.Append('U');
                        break;
                    default:
                        result.Append(c);
                        break;
                }
            }

            return result.ToString();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int sessionId)
        {
            var list = new List<AppBranchListDto>();
            //BURASI
            var items = await _appBranchService.GetBranchListWithSessionId(sessionId);
            foreach (var item in items)
            {
                list.Add(new AppBranchListDto
                {
                    Id = item.Id,
                    Definition = item.Definition
                }); ;
            }
            ViewBag.branches = new SelectList(list, "Id", "Definition");
            ViewBag.sessionId = sessionId;
            return View(new AppOtomationBranchListModel());

        }
        [HttpPost]
        public async Task<IActionResult> BranchDetails(AppOtomationBranchListModel model)
        {
            ViewBag.sessionStatus = await _appSessionService.GetStatusFromSessionId(model.SessionId);
            ViewBag.sessionId = model.SessionId;
            ViewBag.branchId = model.BranchId;
            string branchName = await _appBranchService.BranchNameByByBranchId(model.BranchId);
            ViewBag.branchName = branchName;
            ViewBag.branchName2 = branchName.ToUpper().Replace("/", "_");
            string sessionName = await _appSessionService.ReturnSessionName(model.SessionId);
            ViewBag.sessionName = sessionName;
            ViewBag.sessionName2 = sessionName.ToUpper().Replace("/", "_");
            List<AppOtomationStudentListModel> studentList = new();
            await _appUserSessionService.TotalAverageAllUsers(model.SessionId);

            //BURASI
            var students = await _appStudentService.GetStudentsWithBranchAndSessionAsync(model.BranchId,model.SessionId);


            foreach (var student in students)
            {
                int userSessionId = await _appUserSessionService.UserSessionIdByUserIdAndSessionId(student.Id, model.SessionId);
                double slwc = await _appWarningService.SessionLessonWarningCountByUserSessionId(userSessionId);
                double swc = await _appWarningService.SessionWarningCountByUserSessionId(userSessionId,slwc);
                double twc = await _appWarningService.TotalWarningCountByUserId(student.Id, model.SessionId);
                double awc = await _appWarningService.AbsenteismWarningCountByUserSessionId(userSessionId);
                
                await _appWarningService.ChangeStudentStatusBecasuseOfWarning(student.Id, swc, awc, twc, userSessionId);

                studentList.Add(new AppOtomationStudentListModel
                {
                    FirstName = student.FirstName,
                    SecondName = student.SecondName,
                    StudentId = student.Id,
                    SessionId = model.SessionId,
                    //BURASI
                    Status = await _appUserSessionService.GetUserSessionStatus(userSessionId),

                    BranchSessionDegree = await _appUserSessionService.ReturnSessionOrderOfBranch(student.Id, model.BranchId, model.SessionId),
                    //BURASI

                    BranchDegree = await _appUserSessionService.ReturnTotalOrderOfBranch(student.Id, model.BranchId,model.SessionId),
                    

                    TotalSessionDegree = await _appUserSessionService.ReturnSessionOrderOfClass(student.Id, model.BranchId, model.SessionId),
                    

                    TotalDegree = await _appUserSessionService.ReturnTotalOrderOfClass(student.Id, model.BranchId,model.SessionId),
                    

                    Average = await _appUserSessionService.ReturnSessionAverage(userSessionId),
                    

                    TotalAverage = await _appUserSessionService.ReturnTotalAverage(student.Id),
                    

                    StudentSessionId = await _appUserSessionService.UserSessionIdByUserIdAndSessionId(student.Id, model.SessionId),

                    SessionAbsentWarningCount = await _appWarningService.ReturnAwc(userSessionId),

                    WarningCount = await _appWarningService.ReturnTwc(student.Id),
                    SessionLessonWarningCount=await _appWarningService.SessionLessonWarningCountByUserSessionId(userSessionId),

                    SessionWarningCount = await _appWarningService.ReturnSwc(userSessionId),
                }) ; ;

                double slwc2 = await _appWarningService.SessionLessonWarningCountByUserSessionId(userSessionId);
                double awc2 = await _appWarningService.AbsenteismWarningCountByUserSessionId(userSessionId);
                double swc2 = await _appWarningService.SessionWarningCountByUserSessionId(userSessionId,slwc2);
                double twc2 = await _appWarningService.TotalWarningCountByUserIdGeneral(student.Id);
                await _appWarningService.ChangeStudentStatusBecasuseOfWarning(student.Id, swc2, awc2, twc2, userSessionId);
            }
            string header = $"{sessionName}_{branchName}";



            string headerforPdf = ReplaceMultipleChars(header, charactersToReplace, replacementChar);
            headerforPdf = headerforPdf.ToUpper();

            headerforPdf = ConvertTurkishToEnglish(headerforPdf);
            ViewBag.headerforPdf = headerforPdf;
            return View(studentList);
        }
        [HttpGet]
        public async Task<IActionResult> BranchDetails(int sessionId, int branchId)
        {
            ViewBag.sessionStatus = await _appSessionService.GetStatusFromSessionId(sessionId);
            ViewBag.sessionId = sessionId;
            ViewBag.branchId = branchId;
            string branchName = await _appBranchService.BranchNameByByBranchId(branchId);
            ViewBag.branchName = branchName;
            ViewBag.branchName2 = branchName.ToUpper().Replace("/", "_");
            string sessionName = await _appSessionService.ReturnSessionName(sessionId);
            ViewBag.sessionName = sessionName;
            ViewBag.sessionName2 = sessionName.ToUpper().Replace("/", "_");


            List<AppOtomationStudentListModel> studentList = new();

AKDEM.OBYS.UI/Views/Otomation/BranchDetails.cshtml
@model List<AppOtomationStudentListModel>
@{
    Layout = "_Layout";
    int count = 0;
}
<div class="container-fluid">
    <div id="turnToSession"class="text-left">
        <a class="btn btn-danger" asp-action="SessionDetails" asp-controller="Session" asp-route-id="@ViewBag.sessionId">Döneme Dön</a>
    </div>
    <div class="text-right">
        <a id="pdfButton" class="btn btn-success" asp-action="GenerateAndDownloadPdf" asp-controller="Otomation" asp-route-myFileName="@ViewBag.headerforPdf" asp-route-sessionId="@ViewBag.sessionId" asp-route-branchId="@ViewBag.branchId">PDF</a>
    </div>
    <div class="text-end">
        <h1><span>@($"{ViewBag.sessionName} DÖNEMİ {ViewBag.branchName} SINIFI ")</span></h1>
    </div>

    <p id="paragraph">Genel Ortalama, Genel Sıralama, Toplam İhtar Sayısı gibi nicelikler bu dönem ve bundan önceki dönemlerin verilerine göre hesaplanmıştır. Sonraki dönemlerin verileri bu tabloyu etkilemez.</p>
    <hr />
    <br />
    <table class="mt-3 table table-sm table-hover table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>İsim</th>
                <th>Soyisim</th>
                <th>Dönem Ortalaması</th>
                <th>Genel Ortalama</th>
                <th>Şube Sıralaması(Genel)</th>

                <th>Şube Sıralaması(Dönem)</th>
                <th>Sınıf Sıralaması(Genel)</th>

                <th>Sınıf Sıralaması(Dönem)</th>
                <th>Dönem Ders İhtarları</th>
                <th>Dönem Başarı İhtarları</th>
                <th>Dönem Devamsızlık İhtarları</th>

                <th>Toplam Başarı İhtarları</th>
                <th>Ayrıntılar</th>
                @{if (ViewBag.sessionStatus)
                    {
                        <th>Not İşlemleri</th>
                    } }






            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count = count + 1;
                <tr>
                    <td>@count</td>
                    <td>@item.FirstName</td>
                    <td>@item.SecondName</td>
                    <td>@(item.Average <0 ? "---": @String.Format("{0:0.00}", item.Average))</td>

                    <td>@(item.TotalAverage <0 ? "---": @String.Format("{0:0.00}", item.TotalAverage))</td>

                    @{ if (item.Status)
                        {

                            <td>@(item.BranchDegree == 0 ? "--" : item.BranchDegree.ToString())</td>

                            <td>@(item.BranchSessionDegree == 0 ? "--" : item.BranchSessionDegree.ToString())</td>
                            <td>@(item.TotalDegree == 0 ? "--" : item.TotalDegree.ToString())</td>

                            <td>@(item.TotalSessionDegree == 0 ? "--" : item.TotalSessionDegree.ToString())</td>


                        }
                        else
                        {
                            <td style="font-weight: bold; color: red;"> PASİF</td>
                            <td style="font-weight: bold; color: red;"> PASİF</td>
                            <td style="font-weight: bold; color: red;"> PASİF</td>
                            <td style="font-weight: bold; color: red;"> PASİF</td>




                        }
                    }
                    <td>@item.SessionLessonWarningCount</td>
                    <td>@item.SessionWarningCount</td>
                    <td>@item.SessionAbsentWarningCount</td>
                    <td>@item.WarningCount</td>


                    <td><a class="btn btn-primary" asp-action="StudentDetails" asp-controller="Otomation" asp-route-userSessionId="@item.StudentSessionId">KARNE</a></td>

                    @{if (ViewBag.sessionStatus)
                        {
                            <td><a class="btn btn-danger" asp-action="Notes" asp-controller="Otomation" asp-route-userSessionId="@item.StudentSessionId">Not İşlemleri</a></td>
                        } }






                </tr>
            }
        </tbody>

    </table>

</div>

AKDEM.OBYS.UI/Views/Otomation/Index.cshtml
@model AppOtomationBranchListModel
@{
    Layout = "_Layout";
}


<div class="mb-3">
    <form asp-action="BranchDetails" asp-controller="Otomation" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="SessionId" value="@ViewBag.sessionId" />
        <label>Sınıf :</label>


        <select id="classes" asp-for="BranchId" asp-items="@ViewBag.branches" class="form form-control-sm">
            <option value="0">Bir Sınıf Seçiniz</option>
        </select>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Devam</button>
        </div>



        <div class="mb-3 text-bg-danger" asp-validation-summary="All">

        </div>
    </form>
</div>

AKDEM.OBYS.UI/Views/Otomation/Notes.cshtml
@model List<AppUserSessionLessonUpdateDto>
@{
    Layout = "_Layout";
}

@{
    if (Model.Count != 0)
    {
            <input id="modelCount" type="hidden" value="@Model.Count" />
            <div class="container-fluid">
                <form asp-action="Notes" asp-controller="Otomation" method="post">

                    @for (int i = 0; i < Model.Count; i++)
                {
                        <input type="hidden" asp-for="@Model[i].Id" />
                        <input type="hidden" asp-for="@Model[i].LessonId" />
                        <input type="hidden" asp-for="@Model[i].AppLesson.Definition" />
                        <input type="hidden" asp-for="@Model[i].AppLesson.AppUser.FirstName" />
                        <input type="hidden" asp-for="@Model[i].AppLesson.AppUser.SecondName" />

                        <input type="hidden" asp-for="@Model[i].UserSessionId" />

                        <label class="font-italic font-weight-bold">@Model[i].AppLesson.Definition --> ( @Model[i].AppLesson.AppUser.FirstName @Model[i].AppLesson.AppUser.SecondName )</label>

                        <div class="row">

                            <div class="col-md-4">
                                <label>NOT</label>
                                <br />

                                <input id="visibleInputNot_@i" value="" type="text" class="form-control" placeholder="GİRİLMEDİ" />
                                <input id="hiddenInputNot_@i" type="hidden" asp-for="@Model[i].Not" />
                            </div>
                            <div class="col-md-4">
                                <label>Herhangi Bir Sınav Notu Olmadığı Durumlarda</label>
                                <br />
                                <select asp-for="@Model[i].Status" class="form form-control-sm" id="selectbox_@i">
                                    <option value="0">Not Girmek Yerine; Yalnızca Sonuç </option>
                                    <option value="1">BAŞARILI</option>
                                    <option value="2">BAŞARISIZ</option>
                                </select>
                            </div>



                            <div class="col-md-4">
                                <label>DEVAMSIZLIK</label>
                                <br />
                                <input id="visibleInput_@i" value="" type="text" class="form-control" placeholder="GİRİLMEDİ" />
                                <input id="hiddenInput_@i" type="hidden" asp-for="@Model[i].Devamsızlık" />
                            </div>



                        </div>
                        <hr />
                }
                    <br />


                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Kaydet</button>
                    </div>
                    <div class="mb-3 text-bg-danger" asp-validation-summary="All">
                    </div>
                </form>
            </div>
    }
}
@{
    else
    {

            <p class="font-weight-bold">ÖĞRENCİYE/SINIFA AİT BİR DERS PROGRAMI BİLGİSİ BULUNAMADI</p>
    }
}

@section script
    {

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>

        function handleStatusChange(index) {
            $('#selectbox_' + index).on('click', function () {
                var selectedValue = $(this).val();
                console.log(selectedValue);

                if (selectedValue == "1") {
                    $('#visibleInputNot_' + index).val('').attr('placeholder', 'BAŞARILI');
                    $('#hiddenInputNot_' + index).val(-5);
                }
                else if (selectedValue = "2") {

                    $('#visibleInputNot_' + index).val('').attr('placeholder', 'BAŞARISIZ');
                    $('#hiddenInputNot_' + index).val(-6);
                }
                else {
                    // Eğer "1" veya "2" seçili değilse, normal işlemi devam ettir
                    var notValue = -1;
                    $('#hiddenInputNot_' + index).val(notValue);
                }
            });

        }


        function handleStatusChange2(index) {
            
            console.log("Buradayım");
                    $('#selectbox_' + index).val(0);
                
            

        }


        $(document).ready(function () {


            var modelCount = $('#modelCount').val();

            for (var i = 0; i < modelCount; i++) {
                // Görünür input alanında bir değer girildiğinde
                $('#visibleInputNot_' + i).on('input', function () {
                    var id = $(this).attr('id').split('_')[1];
                    var enteredValue = $(this).val();

                    // Gizli input alanına girilen değeri aktar
                    $('#hiddenInputNot_' + id).val(enteredValue);
                });

                $('#visibleInput_' + i).on('input', function () {
                    var id = $(this).attr('id').split('_')[1];
                    var enteredValue = $(this).val();

                    // Gizli input alanına girilen değeri aktar
                    $('#hiddenInput_' + id).val(enteredValue);
                });

                // Sayfa yüklendiğinde, eğer Not değeri -1 ise "GİRİLMEDİ ALTERNATİF" yazısını görünür input alanına ekle
                var notValue = $('#hiddenInputNot_' + i).val();
                var devamValue = $('#hiddenInput_' + i).val();
                // var statusValue =  = $('#selectbox_' + i).val();

                //     if (statusValue === "1") {
                //         $('#visibleInputNot_' + i).attr('placeholder', 'BAŞARILI');
                //     }
                //     else if (statusValue === "2") {
                //         $('#visibleInput_' + i).attr('placeholder', 'BAŞARISIZ');
                //     }
                console.log(notValue);
                if (notValue == -1) {
                    $('#visibleInputNot_' + i).attr('placeholder', 'GİRİLMEDİ');
                } else if (notValue == -5) {
                    $('#visibleInputNot_' + i).attr('placeholder', 'BAŞARILI');
                }
                else if (notValue == -6) {
                    $('#visibleInputNot_' + i).attr('placeholder', 'BAŞARISIZ');
                }
                else {
                    $('#visibleInputNot_' + i).val(notValue)

                }

                if (devamValue == -1) {
                    $('#visibleInput_' + i).attr('placeholder', 'GİRİLMEDİ');
                } else {
                    $('#visibleInput_' + i).val(devamValue);
                }

                $('#selectbox_' + i).on('change', (function (index) {
                    return function () {

                        console.log(index);
                        handleStatusChange(index);
                    };
                })(i));
                $('#visibleInputNot_' + i).on('keydown', (function (index) {
                    return function () {

                        
                        handleStatusChange2(index);
                    };
                })(i));



            }
        });


    </script>



}

AKDEM.OBYS.UI/Views/Otomation/StudentDetails.cshtml
@model StudentDetailsModel
@{
    Layout = "_Layout";
    int count = 0;

}
<div class="container-fluid">
    <div class="text-right">
        <a id="pdfButton" class="btn btn-success" asp-action="GenerateAndDownloadPdf2" asp-controller="Otomation" asp-route-myFileName="@ViewBag.headerforPdf" asp-route-userSessionId="@ViewBag.userSessionId" asp-route-branchId="@ViewBag.branchId">PDF</a>
    </div>
       
        
            <h2>@Model.AppStudent.FirstName @Model.AppStudent.SecondName    (@ViewBag.sessionName)</h2>
        
        
    
    <hr />
    
    <hr />
    <div class="row">
        <div class="col-md-2">
            <img src="@Model.AppStudent.ImagePath" height="250" width="200" />

        </div>
        <div class="col-md-10">
            <ul class="list-group">

                <li class="list-group-item"><strong>Sınıf:</strong>     @Model.AppStudentSession.AppClass.Definition</li>
                <li class="list-group-item"><strong>Şube:</strong>     @Model.AppStudentSession.AppBranch.Definition</li>
                <li class="list-group-item"><strong>Sıra No:</strong>       @Model.AppStudent.SıraNo</li>
                <li class="list-group-item"><strong>Email:</strong>     @Model.AppStudent.Email</li>
                

                @{ if (Model.AppStudentSession.Status)
                    {
                        <li class="list-group-item">
                            <strong>Durum:</strong> <span style="font-weight: bold; color: lightseagreen;">AKTİF</span>
                        </li>
                    }
                    else
                    {
                        <li class="list-group-item">

                            <strong>Durum:</strong> <span style="font-weight: bold; color: red;">PASİF ( @Model.AppStudent.DepartReason )</span>
                        </li>
                    }
                }

            </ul>
        </div>
    </div>
   
    <table class="mt-3 table table-sm table-hover table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Ders</th>
                <th>Not</th>
                <th>Devamsızlık</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AppUserSessionLessons)
            {
                count = count + 1;
                <tr>
                    <td>@count</td>
                    <td>@item.AppLesson.Definition (@item.AppLesson.AppUser.FirstName @item.AppLesson.AppUser.SecondName )</td>

                    @{if (item.Not == -1)
                        {
                            <td>GİRİLMEDİ</td>
                        }

                    }
                    @{
                        else if (item.Not == -5)
                        {
                            <td>BAŞARILI</td>

                        }
                    }
                    @{
                        else if (item.Not == -6)
                        {
                            <td>BAŞARISIZ</td>

                        }
                    }
                    @{ else
                        {
                            <td>@item.Not</td>
                        }
                    }

                    @{if (item.Devamsızlık == -1)
                        {
                            <td>GİRİLMEDİ</td>
                        }

                    }
                    @{ else
                        {
                            <td>@item.Devamsızlık</td>
                        }
                    }



                </tr>
            }
        </tbody>

    </table>
 
<div class="row">
    <div class="col-md-6">
        <ul class="list-group">
            <li class="list-group-item"><strong>Dönem Ortalaması:</strong> @(Model.AppStudentSession.Average < 0 ? "---": @String.Format("{0:0.00}", Model.AppStudentSession.Average)) </li>

            <li class="list-group-item"><strong>Genel Ortalama:</strong>  @(Model.AppStudentSession.TotalAverage < 0 ? "---": @String.Format("{0:0.00}", Model.AppStudentSession.TotalAverage))</li>


            <li class="list-group-item" style="display: flex; justify-content: space-between;">
                <span><strong>Dönem Ders İhtar Sayısı:</strong> @Model.AppStudentSession.LessonWarningCount</span>
                <span><strong>Dönem Devamsızlık İhtar Sayısı:</strong>   @Model.AppStudentSession.AbsenteismWarningCount</span>
            </li>
            <li class="list-group-item" style="display: flex; justify-content: space-between;">
                <span><strong>Dönem Başarı İhtar Sayısı:</strong> @Model.AppStudentSession.SessionWarningCount</span>
                <span><strong>Genel Başarı İhtar Sayısı:</strong> @Model.AppStudentSession.TotalWarningCount</span>

            </li>


        </ul>
    </div>
    @{if (Model.AppStudentSession.Status)
        {

            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>Şube Sıralaması(Dönem):</strong> @(Model.BranchSessionDegree ==0 ? "--":
 Model.BranchSessionDegree)
                    </li>

                    <li class="list-group-item">
                        <strong>Şube Sıralaması(Genel):</strong>  @(Model.BranchDegree ==0 ? "--":
 Model.BranchDegree)
                    </li>
                    <li class="list-group-item">
                        <strong>Sınıf Sıralaması(Dönem):</strong> @(Model.TotalSessionDegree ==0 ? "--":
 Model.TotalSessionDegree)
                    </li>
                    <li class="list-group-item">
                        <strong>Sınıf Sıralaması(Genel):</strong>   @(Model.TotalDegree ==0 ? "--":
 Model.TotalDegree)
                    </li>


                </ul>
            </div>
        }
        else
        {
            <div class="col-md-6">
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>Şube Sıralaması(Dönem):</strong> PASİF
                    </li>

                    <li class="list-group-item">
                        <strong>Şube Sıralaması(Genel):</strong> PASİF
                    </li>
                    <li class="list-group-item">
                        <strong>Sınıf Sıralaması(Dönem):</strong> PASİF
                    </li>
                    <li class="list-group-item">
                        <strong>Sınıf Sıralaması(Genel):</strong>   PASİF
                    </li>


                </ul>
            </div>
        }
    }

</div>


    <br />
    <a id="btnwarnings" class="btn btn-outline-dark" asp-action="WarningDetails" asp-controller="Otomation" asp-route-sessionId="@Model.AppStudentSession.SessionId" asp-route-userId="@Model.AppStudent.Id">İHTARLAR</a>
    <a id="turnclass" class="btn btn-outline-dark" asp-action="BranchDetails" asp-controller="Otomation" asp-route-sessionId="@Model.AppStudentSession.SessionId" asp-route-branchId="@Model.AppStudent.BranchId">SINIFA DÖN</a>

</div>

AKDEM.OBYS.UI/Views/Otomation/WarningDetails.cshtml
@model StudentWarningsModel
@{
    Layout = "_Layout";
    int count = 0;
}

<div class="mt-2">
    <div class="text-right">
        <a id="pdfButton" class="btn btn-success" asp-action="GenerateAndDownloadPdf" asp-controller="Warning" asp-route-myFileName="@ViewBag.headerforPdf" asp-route-sessionId="@ViewBag.sessionId" asp-route-userId="@ViewBag.userId">PDF</a>
    </div>
    <hr />
    @{ if (!Model.Status)
        {

            <h5>
                <span style=" color: red;">@Model.DepartReason</span>
            </h5>

        }

    }

    <hr />
    <h1>DÖNEM İHTARLARI</h1>
</div>
<table class="mt-3 table table-sm table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>İhtar Katkısı</th>
            <th>İhtar Sebebi</th>
            <th>İhtar Tarihi</th>
            @{if (ViewBag.sessionStatus) { 
                
                        <th>İhtarı Sil</th>
                } }
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AppWarnings)
        {
            count = count + 1;
        <tr>

            <td>@count</td>
            <td>@item.WarningCount</td>
            <td>@item.WarningReason</td>
            <td>@item.WarningTime</td>

            @{if (ViewBag.sessionStatus)
                {

                        <td><a class="btn btn-outline-danger" asp-action="RemoveWarning" asp-controller="Otomation" asp-route-id="@item.Id" asp-route-sessionId="@ViewBag.sessionId" asp-route-userId="@ViewBag.userId">Sil</a></td>
                } }

            





        </tr>
        }
    </tbody>
    

</table>
<a id="turnToStudent"class="btn btn-outline-success" asp-action="StudentDetails" asp-controller="Otomation" asp-route-userSessionId="@ViewBag.userSessionId">Öğrenciye Dön</a>