AKDEM.OBYS.UI/Controllers/ScheduleDetailController.cs
using AKDEM.OBYS.Business.Services;
using AKDEM.OBYS.Common;
using AKDEM.OBYS.Common.Enums;
using AKDEM.OBYS.Dto.AppScheduleDetailDto;
using AKDEM.OBYS.Dto.AppScheduleDtos;
using AKDEM.OBYS.Dto.AppUserSessionDtos;
using AKDEM.OBYS.Dto.AppUserSessionLessonDtos;
using AKDEM.OBYS.UI.Models;
using AutoMapper;
using FluentValidation;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PuppeteerSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AKDEM.OBYS.UI.Controllers
{
    public class ScheduleDetailController : Controller
    {
        private readonly IAppLessonService _appLessonService;
        private readonly IAppScheduleService _appScheduleService;
        private readonly IAppScheduleDetailService _appScheduleDetailService;
        private readonly IMapper _mapper;
        private readonly IAppUserSessionService _appUserSessionService;
        private readonly IAppUserSessionLessonService _appUserSessionLessonService;
        private readonly IAppSessionService _appSessionService;
        private readonly IAppWarningService _appWarningService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        private readonly IValidator<AppScheduleDetailCreateModel> _appScheduleDetailCreateModelValidator;

        public ScheduleDetailController(IAppLessonService appLessonService, IAppScheduleService appScheduleService, IAppScheduleDetailService appScheduleDetailService, IMapper mapper, IAppUserSessionService appUserSessionService, IAppUserSessionLessonService appUserSessionLessonService, IAppSessionService appSessionService, IAppWarningService appWarningService, IValidator<AppScheduleDetailCreateModel> appScheduleDetailCreateModelValidator, IWebHostEnvironment webHostEnvironment)
        {
            _appLessonService = appLessonService;
            _appScheduleService = appScheduleService;
            _appScheduleDetailService = appScheduleDetailService;
            _mapper = mapper;
            _appUserSessionService = appUserSessionService;
            _appUserSessionLessonService = appUserSessionLessonService;
            _appSessionService = appSessionService;
            _appWarningService = appWarningService;
            _appScheduleDetailCreateModelValidator = appScheduleDetailCreateModelValidator;
            _webHostEnvironment = webHostEnvironment;
        }
        char[] charactersToReplace = { '/', ' ', '\\', '?', ':', '.', ',' };
        char replacementChar = '_';
        static string ReplaceMultipleChars(string input, char[] charactersToReplace, char replacementChar)
        {
            foreach (char c in charactersToReplace)
            {
                input = input.Replace(c, replacementChar);
            }
            return input;
        }
        static string ConvertTurkishToEnglish(string input)
        {
            StringBuilder result = new StringBuilder();

            foreach (char c in input)
            {
                switch (c)
                {
                    case 'Ç':
                        result.Append('C');
                        break;
                    case 'Ğ':
                        result.Append('G');
                        break;

                    case 'İ':
                        result.Append('I');
                        break;
                    case 'Ö':
                        result.Append('O');
                        break;
                    case 'Ş':
                        result.Append('S');
                        break;
                    case 'Ü':
                        result.Append('U');
                        break;
                    default:
                        result.Append(c);
                        break;
                }
            }

            return result.ToString();
        }
        public async Task<IActionResult> Index(int id)
        {
            string name = await _appScheduleService.GetNameByScheduleId(id);
            ViewBag.scheduleId = id;
            ViewBag.sessionBranchId = await _appScheduleService.GetSessionBranchIdByAppScheduleId(id);
            int sessionId = await _appScheduleService.GetSessionIdByScheduleId(id);
            string sessionName = await _appSessionService.ReturnSessionName(sessionId);
            ViewBag.sessionName = sessionName;
            ViewBag.sessionName2 = sessionName.Replace("/", "_");
            ViewBag.name = name;
            ViewBag.name2 = name.Replace("/", "_");
            ViewBag.sessionStatus2 = await _appSessionService.GetStatus2FromSessionId(sessionId);


            string header = $"{sessionName}_{name}";
            string headerforPdf = ReplaceMultipleChars(header, charactersToReplace, replacementChar);
            headerforPdf = headerforPdf.ToUpper();
            headerforPdf = ConvertTurkishToEnglish(headerforPdf);
            ViewBag.headerforPdf = headerforPdf;
            return View();
        }

        public async Task<IActionResult> CreateScheduleDetail(int sessionBranchId)
        {
            int sessionId = await _appScheduleService.GetSessionIdBySessionBranchId(sessionBranchId);
            int branchId = await _appScheduleService.GetBranchIdBySessionBranchId(sessionBranchId);
            int scheduleId = await _appScheduleService.GetAppScheduleIdBySessionBranchIdAsync(sessionBranchId);

            var list = new List<AppScheduleDetailLessonModel>();
            var items = await _appLessonService.GetLessonsByTeacher(true);
            foreach (var item in items)
            {
                list.Add(new AppScheduleDetailLessonModel
                {
                    Id = item.Id,
                    LessonDetail = $"{item.Definition}--{item.AppUser.FirstName} {item.AppUser.SecondName}"

                });

            }
            ViewBag.lessons = new SelectList(list, "Id", "LessonDetail");

            var list2 = new List<AppScheduleDetailWeekDaysModel>();
            var items2 = Enum.GetValues(typeof(WeekDaysType));
            foreach (var item in items2)
            {
                list2.Add(new AppScheduleDetailWeekDaysModel
                {
                    Day = Enum.GetName(typeof(WeekDaysType), item),
                    DayVal = Enum.GetName(typeof(WeekDaysType), item)

                });
            }
            ViewBag.days = new SelectList(list2, "Day", "DayVal");
            ViewBag.scheduleId = scheduleId;
            ViewBag.sessionId = sessionId;
            //ViewBag.branchId = branchId;
            return View(new AppScheduleDetailCreateModel { SessionId = sessionId, BranchId = branchId, ApScheduleId = scheduleId });
        }
        [HttpPost]
        public async Task<IActionResult> CreateScheduleDetail(AppScheduleDetailCreateModel model)
        {
            ViewBag.scheduleId = model.ApScheduleId;

            //int sessionId = await _appScheduleService.GetSessionIdByScheduleId(model.ApScheduleId);
            //------------------SELECTBOXLAR-----------------
            var list = new List<AppScheduleDetailLessonModel>();
            var items = await _appLessonService.GetLessonsByTeacher(true);
            foreach (var item in items)
            {
                list.Add(new AppScheduleDetailLessonModel
                {
                    Id = item.Id,
                    LessonDetail = $"{item.Definition}--{item.AppUser.FirstName} {item.AppUser.SecondName}"

                });

            }
            ViewBag.lessons = new SelectList(list, "Id", "LessonDetail");

            var list2 = new List<AppScheduleDetailWeekDaysModel>();
            var items2 = Enum.GetValues(typeof(WeekDaysType));
            foreach (var item in items2)
            {
                list2.Add(new AppScheduleDetailWeekDaysModel
                {
                    Day = Enum.GetName(typeof(WeekDaysType), item),
                    DayVal = Enum.GetName(typeof(WeekDaysType), item)

                });
            }
            ViewBag.days = new SelectList(list2, "Day", "DayVal");

            //----------SELECTBOXLAR------------------


            var modelResult = _appScheduleDetailCreateModelValidator.Validate(model);
            if (modelResult.IsValid)
            {
                AppScheduleDetailCreateDto dto = new();
                dto.ApScheduleId = model.ApScheduleId;
                dto.Day = model.Day;
                dto.Hours = $"{model.FirstHour}-{model.LastHour}";
                dto.LessonId = model.LessonId;
                var result = await _appScheduleDetailService.CreateAsync(dto);

                if (result.ResponseType == ResponseType.Success)
                {

                    //ViewBag.sessionId = sessionId;
                    ViewBag.confirmMessage = 1;
                    ViewBag.alertMessage = "Ders Bilgisi Cizelgeye Basariyla Eklenmistir. Yeni Dersler Eklemeye Devam Edebilirsiniz";
                    return View(new AppScheduleDetailCreateModel());
                }
                else
                {



                    foreach (var error in result.ValidationErrors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                    return View(result.Data);

                }
            }

            foreach (var error in modelResult.Errors)
            {
                ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
            }
            return View(model);


        }

        [HttpGet]
        public async Task<IActionResult> GetScheduleDetailandHours(int scheduleId)
        {
            var hourList = await _appScheduleDetailService.GetHoursByScheduleIdAsync(scheduleId);
            var scheduleDetailList = await _appScheduleDetailService.GetScheduleDetailsByScheduleId(scheduleId);

AKDEM.OBYS.UI/Views/ScheduleDetail/CreateScheduleDetail.cshtml
@model AppScheduleDetailCreateModel
@{
    Layout = "_Layout";
}
@section style{
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
    </style>

}
<h2>Çizelge Oluştur</h2>
<br />
<br />

<div class="text-right">
    <a class="btn btn-outline-info" asp-action="CreateSchedule" asp-controller="Schedule" asp-route-id="@ViewBag.sessionId">Yeni Program</a>

    <a class="btn btn-outline-secondary" asp-action="Index" asp-controller="Schedule" asp-route-id="@ViewBag.sessionId">Tüm Programlar</a>
</div>

<br />
<div class="container-fluid">
    <form asp-action="CreateScheduleDetail" asp-controller="ScheduleDetail" method="post" enctype="multipart/form-data">
        <input type="hidden" asp-for="SessionId" />
        <input type="hidden" asp-for="BranchId" />
        <input type="hidden" asp-for="ApScheduleId" />

        <div class="row">
            <div class="col-md-3">
                <select asp-for="LessonId" asp-items="@ViewBag.lessons" class="form form-control-sm">
                    <option value="0">Bir Ders Seçiniz</option>
                </select>
            </div>
            <div class="col-md-3">
                <select asp-for="Day" asp-items="@ViewBag.days" class="form form-control-sm">
                    <option value="0">Bir Gün Seçiniz</option>
                </select>
            </div>
            <div class="col-md-3">
                <label>Başlangıç :</label>
                <input type="time" asp-for="FirstHour" />
            </div>
            <div class="col-md-3">
                <label>Bitiş :</label>
                <input type="time" asp-for="LastHour" />
            </div>
        </div>
        <br />

        <div class="mt-3">
            <button class="btn btn-success" type="submit">EKLE</button>
        </div>
        <div class="mb-3 text-bg-danger" asp-validation-summary="All">

        </div>
        <br />
    </form>
</div>




<table id="dersProgramiTable">
    <thead>
        <tr>
            <th>Saat</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
<br />
<br />
<br />
<table style="max-width:500px" id="dersProgramiOnizle" class="table-borderless  ">
    <tbody>
    </tbody>
</table>
<div class="text-right">
    <a class="btn btn-outline-info" asp-action="SaveChanges" asp-controller="ScheduleDetail" asp-route-scheduleId="@ViewBag.scheduleId">KAYDET</a>

</div>


@section script{

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>



    
    <script>

        @*$(document).ready(function () {
            setUpPage();
            console.log("Selam");
        });
            function setUpPage() {

                var gunler = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma","Cumartesi","Pazar"];

        var baslikSatiri = $("<tr>").append("<th>Saat</th>");
        gunler.forEach(function (gun) {
            baslikSatiri.append("<th>" + gun + "</th>");
        });
        $("#dersProgramiTable thead tr").remove();
        $("#dersProgramiTable thead").append(baslikSatiri);





        $.get('/ScheduleDetail/GetScheduleDetailandHours', { scheduleId: @ViewBag.scheduleId }, function (data) {
                // Şube ayrıntılarını güncelle

                updateTable(data);
        });
        $.get('/ScheduleDetail/GetScheduleDetailandHours', { scheduleId: @ViewBag.scheduleId }, function (data) {
                // Şube ayrıntılarını güncelle

                updateTable2(data);
        });

            }*@
        var gunler = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma","Cumartesi","Pazar"];

        var baslikSatiri = $("<tr>").append("<th>Saat</th>");
        gunler.forEach(function (gun) {
            baslikSatiri.append("<th>" + gun + "</th>");
        });
        $("#dersProgramiTable thead tr").remove();
        $("#dersProgramiTable thead").append(baslikSatiri);





        $.get('/ScheduleDetail/GetScheduleDetailandHours', { scheduleId: @ViewBag.scheduleId }, function (data) {
                // Şube ayrıntılarını güncelle

                updateTable(data);
        });
        $.get('/ScheduleDetail/GetScheduleDetailandHours', { scheduleId: @ViewBag.scheduleId }, function (data) {
                // Şube ayrıntılarını güncelle

                updateTable2(data);
        });





        function updateTable(data) {
            // Tabloyu temizle
            $("#dersProgramiTable tbody").empty();


            // Saat aralıkları üzerinde döngü
            $.each(data.scheduleHours, function (index, saat) {
                var satir = $("<tr>").append("<td>" + saat + "</td>");


                // Günler üzerinde döngü
                gunler.forEach(function (gun) {
                    // İlgili gün ve saatteki dersi bul
                    var ders = data.appScheduleDetails.find(x => x.day == gun && x.hours == saat);

                    // Ders bilgisini al

                    var dersBilgisi = ders ? ders.appLesson.definition : "";
                    var saatBilgisi = ders ? `(\n${saat})`: "";



                    satir.append("<td>" + dersBilgisi +   saatBilgisi  + "</td>");


                });




                // Satırı tabloya ekle
                $("#dersProgramiTable tbody").append(satir);


            });



        }
        let derslerSet = new Set();
        let dtoSet = new Set();

        function updateTable2(data) {



            $.each(data.appScheduleDetails, function (index, dto) {

                dtoSet.add(dto);

            });

            console.log(dtoSet);

            $("#dersProgramiOnizle tbody").empty();
            $.each(data.appScheduleDetails, function (index, dto) {
                var dersler = dto.appLesson.definition;
                derslerSet.add(dersler);

            });
            var uniqueDerslerArray = Array.from(derslerSet);
            var dtoarray = Array.from(dtoSet);


            uniqueDerslerArray.forEach(function (ders,index) {
                var satir = $("<tr>").append("<td>" + "-->" + "</td>").addClass(" font-weight-bold")
                var dersSatir = $("<td>").text(ders).addClass(" font-weight-bolder")
                var lesson = dtoarray.find(x => x.appLesson.definition == ders);

                var id = lesson.ıd;


                satir.append(dersSatir);
                var link1 = $('<a>').text("X")
                    .attr('href', '/ScheduleDetail/RemoveScheduleDetail?id='+id)
                    .addClass("btn btn-outline-danger text-danger font-weight-bold");

                satir.append(link1);

                $("#dersProgramiOnizle tbody").append(satir);
            });
        }

    </script>
    



}

AKDEM.OBYS.UI/Views/ScheduleDetail/Index.cshtml
@{
    Layout = "_Layout";
}
@section style{
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
    </style>

}
<h2>@ViewBag.name</h2>
<div class="text-right">
    <a id="pdfButton" class="btn btn-success" asp-action="GenerateAndDownloadPdf" asp-controller="ScheduleDetail" asp-route-myFileName="@ViewBag.headerforPdf" asp-route-scheduleId="@ViewBag.scheduleId" asp-route-userId="@ViewBag.userId">PDF</a>
</div>
<br />
@{ if (ViewBag.sessionStatus2)
    {
        <div id="buttondiv" class="text-right">
            <a class="btn btn-outline-info" asp-action="CreateScheduleDetail" asp-controller="ScheduleDetail" asp-route-sessionBranchId="@ViewBag.sessionBranchId">Programı Güncelle</a>

            <a class="btn btn-outline-danger" asp-action="RemoveSchedule" asp-controller="Schedule" asp-route-scheduleId="@ViewBag.scheduleId">Programı Sil</a>
        </div>
    }

}

<br />
<table id="dersProgramiTable">
    <thead>
        <tr>
            <th>Saat</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>




@section script{

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <script>


        var gunler = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma","Cumartesi","Pazar"];

        var baslikSatiri = $("<tr>").append("<th>Saat</th>");
        gunler.forEach(function (gun) {
            baslikSatiri.append("<th>" + gun + "</th>");
        });
        $("#dersProgramiTable thead tr").remove();
        $("#dersProgramiTable thead").append(baslikSatiri);





        $.get('/ScheduleDetail/GetScheduleDetailandHours', { scheduleId: @ViewBag.scheduleId }, function (data) {
                // Şube ayrıntılarını güncelle

                updateTable(data);
            });




        function updateTable(data) {
            // Tabloyu temizle
            $("#dersProgramiTable tbody").empty();


            // Saat aralıkları üzerinde döngü
            $.each(data.scheduleHours, function (index, saat) {
                var satir = $("<tr>").append("<td>" + saat + "</td>");
                console.log(saat);

                // Günler üzerinde döngü
                gunler.forEach(function (gun) {
                    // İlgili gün ve saatteki dersi bul
                    var ders = data.appScheduleDetails.find(x => x.day == gun && x.hours == saat);

                    // Ders bilgisini al
                    var dersBilgisi = ders ? ders.appLesson.definition : "";
                    var saatBilgisi = ders ? `(\n${saat})` : "";



                    satir.append("<td>" + dersBilgisi + saatBilgisi + "</td>");


                });




                // Satırı tabloya ekle
                $("#dersProgramiTable tbody").append(satir);


            });



        }

    </script>


}